name: Run Event Calendar Scripts

# Dispara el workflow cada 7 minutos o manualmente
on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Event Calendar Script
        run: node scripts/methodCalendar/eventCalendar.js
        env:
          AIRTABLE_TKN: ${{ secrets.AIRTABLE_TKN }}
          AIRTABLE_BSID: ${{ secrets.AIRTABLE_BSID }}
          AIRTABLE_TBL_CITA: ${{ secrets.AIRTABLE_TBL_CITA }}
          AIRTABLE_TBL_PACIENTE: ${{ secrets.AIRTABLE_TBL_PACIENTE }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run Update Event Calendar Script
        run: node scripts/methodCalendar/updateEventCalendar.js
        env:
          AIRTABLE_TKN: ${{ secrets.AIRTABLE_TKN }}
          AIRTABLE_BSID: ${{ secrets.AIRTABLE_BSID }}
          AIRTABLE_TBL_CITA: ${{ secrets.AIRTABLE_TBL_CITA }}
          AIRTABLE_TBL_PACIENTE: ${{ secrets.AIRTABLE_TBL_PACIENTE }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run Delete Calendar Script
        run: node scripts/methodCalendar/deleteCalendar.js
        env:
          AIRTABLE_TKN: ${{ secrets.AIRTABLE_TKN }}
          AIRTABLE_BSID: ${{ secrets.AIRTABLE_BSID }}
          AIRTABLE_TBL_CITA: ${{ secrets.AIRTABLE_TBL_CITA }}
          AIRTABLE_TBL_PACIENTE: ${{ secrets.AIRTABLE_TBL_PACIENTE }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
